### ISSUE TITLE
"invalid literal for int() with base 10:" when i input for server

### ISSUE THREAD

**Issue by Purkid** [FireHead90544/gogoanime-dl#2]
What input is it expecting i should put when I select what server should I use ?
i tried to input the name of the server (xstreamcdn,vidstreaming, gogo server, doodstream, streamsb) and I get an error "invalid literal for int() with base 10:". 
Is there supposed to be a list of servers that indicate what I place as input?

**Comment by FireHead90544** [comment]
Heyaa there, since this project has already been obselete, I won't be able to help much. Try playing around with print statements around inputs and get your desired output.
But gogoanime has changed a lot since the time of release of this, so it won't be wise to use this now.

**Comment by Purkid** [comment]
I see, i guess i'll try my luck elsewhere. Maybe i'll use your newer program and understand it along the way. I don't have that much knowledge on stuffs that involves coding so I'm thankful for projects like yours that make the internet easier for people like myself. 
Thank you and happy holidays.

**Comment by FireHead90544** [comment]
Wish you good luck with em, feel free to raise an issue if you need some help with the newer program. Learning never stops, it's pretty easy if you've got the interest. You've got this. Thank you 🙂
